// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            []byte             `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserId               string             `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	TotalPrice           float64            `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Books                []*Order_OrderBook `protobuf:"bytes,5,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetCreatedAt() []byte {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetTotalPrice() float64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetBooks() []*Order_OrderBook {
	if m != nil {
		return m.Books
	}
	return nil
}

type Order_OrderBook struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Isbn                 string   `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             uint32   `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderBook) Reset()         { *m = Order_OrderBook{} }
func (m *Order_OrderBook) String() string { return proto.CompactTextString(m) }
func (*Order_OrderBook) ProtoMessage()    {}
func (*Order_OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0, 0}
}

func (m *Order_OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderBook.Unmarshal(m, b)
}
func (m *Order_OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderBook.Marshal(b, m, deterministic)
}
func (m *Order_OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderBook.Merge(m, src)
}
func (m *Order_OrderBook) XXX_Size() int {
	return xxx_messageInfo_Order_OrderBook.Size(m)
}
func (m *Order_OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderBook proto.InternalMessageInfo

func (m *Order_OrderBook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order_OrderBook) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Order_OrderBook) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Order_OrderBook) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Order_OrderBook) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order_OrderBook) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	UserId               string                          `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Books                []*CreateOrderRequest_OrderBook `protobuf:"bytes,4,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateOrderRequest) GetBooks() []*CreateOrderRequest_OrderBook {
	if m != nil {
		return m.Books
	}
	return nil
}

type CreateOrderRequest_OrderBook struct {
	BookId               string   `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest_OrderBook) Reset()         { *m = CreateOrderRequest_OrderBook{} }
func (m *CreateOrderRequest_OrderBook) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest_OrderBook) ProtoMessage()    {}
func (*CreateOrderRequest_OrderBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1, 0}
}

func (m *CreateOrderRequest_OrderBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest_OrderBook.Unmarshal(m, b)
}
func (m *CreateOrderRequest_OrderBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest_OrderBook.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest_OrderBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest_OrderBook.Merge(m, src)
}
func (m *CreateOrderRequest_OrderBook) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest_OrderBook.Size(m)
}
func (m *CreateOrderRequest_OrderBook) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest_OrderBook.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest_OrderBook proto.InternalMessageInfo

func (m *CreateOrderRequest_OrderBook) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *CreateOrderRequest_OrderBook) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetOrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type GetOrdersForUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersForUserRequest) Reset()         { *m = GetOrdersForUserRequest{} }
func (m *GetOrdersForUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrdersForUserRequest) ProtoMessage()    {}
func (*GetOrdersForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *GetOrdersForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersForUserRequest.Unmarshal(m, b)
}
func (m *GetOrdersForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersForUserRequest.Marshal(b, m, deterministic)
}
func (m *GetOrdersForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersForUserRequest.Merge(m, src)
}
func (m *GetOrdersForUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrdersForUserRequest.Size(m)
}
func (m *GetOrdersForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersForUserRequest proto.InternalMessageInfo

func (m *GetOrdersForUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetOrdersForUserResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrdersForUserResponse) Reset()         { *m = GetOrdersForUserResponse{} }
func (m *GetOrdersForUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrdersForUserResponse) ProtoMessage()    {}
func (*GetOrdersForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *GetOrdersForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrdersForUserResponse.Unmarshal(m, b)
}
func (m *GetOrdersForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrdersForUserResponse.Marshal(b, m, deterministic)
}
func (m *GetOrdersForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrdersForUserResponse.Merge(m, src)
}
func (m *GetOrdersForUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrdersForUserResponse.Size(m)
}
func (m *GetOrdersForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrdersForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrdersForUserResponse proto.InternalMessageInfo

func (m *GetOrdersForUserResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Order_OrderBook)(nil), "pb.Order.OrderBook")
	proto.RegisterType((*CreateOrderRequest)(nil), "pb.CreateOrderRequest")
	proto.RegisterType((*CreateOrderRequest_OrderBook)(nil), "pb.CreateOrderRequest.OrderBook")
	proto.RegisterType((*CreateOrderResponse)(nil), "pb.CreateOrderResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "pb.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "pb.GetOrderResponse")
	proto.RegisterType((*GetOrdersForUserRequest)(nil), "pb.GetOrdersForUserRequest")
	proto.RegisterType((*GetOrdersForUserResponse)(nil), "pb.GetOrdersForUserResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x8f, 0x93, 0x40,
	0x1c, 0x75, 0x68, 0xa1, 0xf2, 0x63, 0xfd, 0x93, 0x59, 0xb3, 0x4c, 0x70, 0xa3, 0x2c, 0x27, 0xbc,
	0xf4, 0xc0, 0x26, 0x7b, 0x33, 0x59, 0xd7, 0x44, 0xb3, 0xa7, 0x9a, 0x31, 0x5e, 0xbc, 0x18, 0x28,
	0x93, 0x48, 0xda, 0x74, 0xe8, 0xcc, 0x60, 0xe2, 0xa7, 0xf0, 0x33, 0x78, 0x32, 0xf1, 0x53, 0x9a,
	0xf9, 0x01, 0x2d, 0x2d, 0x35, 0xd9, 0x0b, 0xe1, 0xbd, 0xf9, 0xfd, 0x79, 0xef, 0x0d, 0x40, 0x20,
	0x55, 0x29, 0xd4, 0xbc, 0x56, 0xd2, 0x48, 0xea, 0xd4, 0x45, 0xf2, 0xd7, 0x01, 0x77, 0x61, 0x39,
	0xfa, 0x14, 0x9c, 0xaa, 0x64, 0x24, 0x26, 0xa9, 0xcf, 0x9d, 0xaa, 0xa4, 0x97, 0xe0, 0x2f, 0x95,
	0xc8, 0x8d, 0x28, 0xdf, 0x19, 0xe6, 0xc4, 0x24, 0x3d, 0xe3, 0x7b, 0x82, 0x5e, 0x80, 0xd7, 0x68,
	0xa1, 0xee, 0x4b, 0x36, 0xc1, 0x8e, 0x0e, 0xd1, 0x57, 0x00, 0x46, 0x9a, 0x7c, 0xfd, 0x49, 0x55,
	0x4b, 0xc1, 0xa6, 0x31, 0x49, 0x09, 0x1f, 0x30, 0xf4, 0x0d, 0xb8, 0x85, 0x94, 0x2b, 0xcd, 0xdc,
	0x78, 0x92, 0x06, 0xd9, 0xf9, 0xbc, 0x2e, 0xe6, 0xb8, 0xbf, 0x7d, 0xde, 0x49, 0xb9, 0xe2, 0x6d,
	0x45, 0xf4, 0x8b, 0x80, 0xbf, 0x23, 0x47, 0xf2, 0x28, 0x4c, 0x2b, 0x5d, 0x6c, 0x50, 0x99, 0xcf,
	0xf1, 0x9d, 0xbe, 0x00, 0xd7, 0x54, 0x66, 0x2d, 0x3a, 0x4d, 0x2d, 0xb0, 0x52, 0xf3, 0xc6, 0x7c,
	0x97, 0x0a, 0xe5, 0xf8, 0xbc, 0x43, 0xb6, 0xba, 0x46, 0x95, 0x2e, 0xaa, 0x6c, 0x01, 0x8d, 0xe0,
	0xf1, 0xb6, 0xc9, 0x37, 0xa6, 0x32, 0x3f, 0x99, 0x17, 0x93, 0xf4, 0x09, 0xdf, 0xe1, 0xe4, 0x0f,
	0x01, 0xfa, 0x1e, 0x23, 0x40, 0x5d, 0x5c, 0x6c, 0x1b, 0xa1, 0x0d, 0x0d, 0x61, 0x66, 0xdd, 0x7f,
	0xab, 0xca, 0x4e, 0x4d, 0x1f, 0xc6, 0x4d, 0x6f, 0x76, 0x8a, 0x66, 0x63, 0x6b, 0x76, 0xdc, 0x3f,
	0x76, 0x7e, 0x3b, 0x34, 0x1e, 0xc2, 0xcc, 0xb2, 0x83, 0xe9, 0x16, 0xde, 0x97, 0x07, 0x4a, 0x27,
	0x47, 0x4a, 0x6f, 0xe0, 0xfc, 0x60, 0x91, 0xae, 0xe5, 0x46, 0x0b, 0xfa, 0x1a, 0x5c, 0xfc, 0x00,
	0x30, 0xc7, 0x20, 0xf3, 0x77, 0xe9, 0xf3, 0x96, 0x4f, 0xae, 0xe0, 0xd9, 0x47, 0x61, 0x0e, 0xdc,
	0x1d, 0x05, 0x9f, 0x5c, 0xc3, 0xf3, 0x7d, 0xc9, 0x43, 0xe7, 0x66, 0x10, 0xf6, 0x4d, 0xfa, 0x83,
	0x54, 0x5f, 0xf4, 0xc9, 0xf4, 0xc8, 0x30, 0xbd, 0xe4, 0x2d, 0xb0, 0x71, 0x4f, 0xb7, 0xf0, 0x0a,
	0x3c, 0x1c, 0xac, 0x19, 0xc1, 0x68, 0x07, 0x1b, 0xbb, 0x83, 0xec, 0x37, 0x81, 0x33, 0x64, 0x3e,
	0x0b, 0xf5, 0xc3, 0xde, 0xec, 0x2d, 0x04, 0x83, 0x4c, 0xe8, 0xc5, 0xe9, 0xdb, 0x88, 0xc2, 0x11,
	0xdf, 0xee, 0x4c, 0x1e, 0xd1, 0xc5, 0xde, 0x7a, 0xaf, 0x88, 0xbe, 0xb4, 0xe5, 0xff, 0xf1, 0x16,
	0x5d, 0x9e, 0x3e, 0xec, 0x07, 0xde, 0xf9, 0x5f, 0x67, 0xa8, 0xb6, 0x2e, 0x0a, 0x0f, 0xff, 0xc9,
	0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x21, 0x54, 0xfa, 0xa2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetOrdersForUser(ctx context.Context, in *GetOrdersForUserRequest, opts ...grpc.CallOption) (*GetOrdersForUserResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersForUser(ctx context.Context, in *GetOrdersForUserRequest, opts ...grpc.CallOption) (*GetOrdersForUserResponse, error) {
	out := new(GetOrdersForUserResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/GetOrdersForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetOrdersForUser(context.Context, *GetOrdersForUserRequest) (*GetOrdersForUserResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) GetOrdersForUser(ctx context.Context, req *GetOrdersForUserRequest) (*GetOrdersForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersForUser not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/GetOrdersForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersForUser(ctx, req.(*GetOrdersForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetOrdersForUser",
			Handler:    _OrderService_GetOrdersForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
