// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalogpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Isbn                 string   `protobuf:"bytes,2,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Price                float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateBookRequest struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *CreateBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateBookRequest) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *CreateBookRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateBookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookResponse) Reset()         { *m = CreateBookResponse{} }
func (m *CreateBookResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookResponse) ProtoMessage()    {}
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *CreateBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookResponse.Unmarshal(m, b)
}
func (m *CreateBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookResponse.Merge(m, src)
}
func (m *CreateBookResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookResponse.Size(m)
}
func (m *CreateBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookResponse proto.InternalMessageInfo

func (m *CreateBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetBookRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBooksRequest) Reset()         { *m = GetBooksRequest{} }
func (m *GetBooksRequest) String() string { return proto.CompactTextString(m) }
func (*GetBooksRequest) ProtoMessage()    {}
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *GetBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBooksRequest.Unmarshal(m, b)
}
func (m *GetBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBooksRequest.Marshal(b, m, deterministic)
}
func (m *GetBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBooksRequest.Merge(m, src)
}
func (m *GetBooksRequest) XXX_Size() int {
	return xxx_messageInfo_GetBooksRequest.Size(m)
}
func (m *GetBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBooksRequest proto.InternalMessageInfo

type GetBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBooksResponse) Reset()         { *m = GetBooksResponse{} }
func (m *GetBooksResponse) String() string { return proto.CompactTextString(m) }
func (*GetBooksResponse) ProtoMessage()    {}
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *GetBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBooksResponse.Unmarshal(m, b)
}
func (m *GetBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBooksResponse.Marshal(b, m, deterministic)
}
func (m *GetBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBooksResponse.Merge(m, src)
}
func (m *GetBooksResponse) XXX_Size() int {
	return xxx_messageInfo_GetBooksResponse.Size(m)
}
func (m *GetBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBooksResponse proto.InternalMessageInfo

func (m *GetBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "pb.Book")
	proto.RegisterType((*CreateBookRequest)(nil), "pb.CreateBookRequest")
	proto.RegisterType((*CreateBookResponse)(nil), "pb.CreateBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "pb.GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "pb.GetBookResponse")
	proto.RegisterType((*GetBooksRequest)(nil), "pb.GetBooksRequest")
	proto.RegisterType((*GetBooksResponse)(nil), "pb.GetBooksResponse")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89) }

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x4d, 0xd7, 0x0d, 0xf7, 0xa6, 0xd3, 0x3d, 0xe7, 0x08, 0x43, 0xa4, 0xe4, 0xb4, 0xd3,
	0x84, 0x7a, 0x11, 0xc4, 0xcb, 0x26, 0x88, 0xe0, 0x69, 0xde, 0xbc, 0x35, 0x5b, 0xd0, 0xd0, 0xd1,
	0xc4, 0x26, 0x13, 0xfc, 0x82, 0x7e, 0x2e, 0x69, 0xfa, 0x67, 0xed, 0xec, 0xc1, 0x5b, 0xdf, 0xaf,
	0xef, 0xbd, 0xdf, 0x7b, 0x49, 0xe0, 0x74, 0x1d, 0xd9, 0x68, 0xab, 0xde, 0xe7, 0x3a, 0x55, 0x56,
	0xa1, 0xa7, 0x39, 0x4b, 0xc0, 0x5f, 0x28, 0x15, 0xe3, 0x10, 0x3c, 0xb9, 0xa1, 0x24, 0x20, 0xb3,
	0xfe, 0xca, 0x93, 0x1b, 0x44, 0xf0, 0xa5, 0xe1, 0x09, 0xf5, 0x1c, 0x71, 0xdf, 0x38, 0x86, 0xae,
	0x95, 0x76, 0x2b, 0x68, 0xc7, 0xc1, 0x3c, 0xc0, 0x09, 0xf4, 0xa2, 0x9d, 0xfd, 0x50, 0x29, 0xf5,
	0x1d, 0x2e, 0xa2, 0x2c, 0x5b, 0xa7, 0x72, 0x2d, 0x68, 0x37, 0x20, 0x33, 0xb2, 0xca, 0x03, 0x16,
	0xc3, 0x68, 0x99, 0x8a, 0xc8, 0x8a, 0xcc, 0xba, 0x12, 0x9f, 0x3b, 0x61, 0x6c, 0x25, 0x23, 0x6d,
	0x32, 0xaf, 0x5d, 0xd6, 0x69, 0x97, 0xf9, 0x75, 0x59, 0x08, 0x58, 0x97, 0x19, 0xad, 0x12, 0x23,
	0xf0, 0x0a, 0x7c, 0xae, 0x54, 0xec, 0x6c, 0x83, 0xf0, 0x78, 0xae, 0xf9, 0xdc, 0xfd, 0x77, 0x94,
	0x05, 0x30, 0x7c, 0x12, 0xb6, 0x3e, 0xdd, 0xc1, 0xd1, 0xb0, 0x1b, 0x38, 0xab, 0x32, 0xfe, 0xd5,
	0x72, 0x54, 0x15, 0x98, 0xa2, 0x27, 0x0b, 0xe1, 0x7c, 0x8f, 0x8a, 0x26, 0xd7, 0xd0, 0xcd, 0xd2,
	0x0d, 0x25, 0x41, 0xa7, 0xd1, 0x25, 0xc7, 0xe1, 0x0f, 0x81, 0xe1, 0x32, 0xbf, 0xc0, 0x57, 0x91,
	0x7e, 0xc9, 0xb5, 0xc0, 0x07, 0x80, 0xfd, 0x82, 0x78, 0x99, 0x55, 0xfc, 0x39, 0xdd, 0xe9, 0xe4,
	0x10, 0xe7, 0x3e, 0x76, 0x84, 0x77, 0x30, 0x28, 0xa6, 0x58, 0x7c, 0x3f, 0x3f, 0x22, 0x66, 0x89,
	0xcd, 0xe5, 0xa7, 0x17, 0x0d, 0x56, 0x55, 0xde, 0xc3, 0x49, 0x39, 0xff, 0x8b, 0x34, 0x16, 0xeb,
	0x69, 0xe5, 0x92, 0xd3, 0x71, 0x13, 0x96, 0xc5, 0x8b, 0xc1, 0x5b, 0xbf, 0x78, 0x88, 0x9a, 0xf3,
	0x9e, 0x7b, 0x8b, 0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xaf, 0xb0, 0x68, 0x9c, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatalogServiceClient interface {
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error)
	GetBookByID(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	GetBooksList(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*GetBooksResponse, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookResponse, error) {
	out := new(CreateBookResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetBookByID(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/GetBookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetBooksList(ctx context.Context, in *GetBooksRequest, opts ...grpc.CallOption) (*GetBooksResponse, error) {
	out := new(GetBooksResponse)
	err := c.cc.Invoke(ctx, "/pb.CatalogService/GetBooksList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
type CatalogServiceServer interface {
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookResponse, error)
	GetBookByID(context.Context, *GetBookRequest) (*GetBookResponse, error)
	GetBooksList(context.Context, *GetBooksRequest) (*GetBooksResponse, error)
}

// UnimplementedCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCatalogServiceServer struct {
}

func (*UnimplementedCatalogServiceServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*CreateBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedCatalogServiceServer) GetBookByID(ctx context.Context, req *GetBookRequest) (*GetBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookByID not implemented")
}
func (*UnimplementedCatalogServiceServer) GetBooksList(ctx context.Context, req *GetBooksRequest) (*GetBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooksList not implemented")
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetBookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetBookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/GetBookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetBookByID(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetBooksList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetBooksList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CatalogService/GetBooksList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetBooksList(ctx, req.(*GetBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _CatalogService_CreateBook_Handler,
		},
		{
			MethodName: "GetBookByID",
			Handler:    _CatalogService_GetBookByID_Handler,
		},
		{
			MethodName: "GetBooksList",
			Handler:    _CatalogService_GetBooksList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
